version: 0.2
# try and load secrets as env vars 
env:
  secrets-manager:
    access_key: "arn:aws:secretsmanager:eu-central-1:654654627826:secret:access_key-GNbp0e"
    secret_key: "arn:aws:secretsmanager:eu-central-1:654654627826:secret:secret_key-yU41MM"
phases:
  pre_build:
    commands:
      - echo Retrieving AWS credentials from Secrets Manager...
      - export SECRETS=$(aws secretsmanager --region eu-central-1 get-secret-value --secret-id aws-creds --query SecretString --output text)
      - export AWS_ACCESS_KEY_ID=$(echo $SECRETS | jq -r '.AWS_ACCESS_KEY_ID')
      - export AWS_SECRET_ACCESS_KEY=$(echo $SECRETS | jq -r '.AWS_SECRET_ACCESS_KEY')
      - docker build -t terraform-shell .
      #- echo $secret_key # is showing in cloudwatch as ***, which seems pretty okay  of cloudbuild logging 
      #- echo $access_key
  build:
    commands:
      #- docker images
      - docker run \
          terraform-shell /bin/ls
      # - docker run --rm \
      #     -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
      #     -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
      #     -w /terraform \
      #     terraform-shell terraform apply --auto-approve
          # -w /terraform \
          # -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
          # -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
# trying to get it to do anything based on created docker image, directory listing is shown when command = docker run terraform-shell /bin/pwd;/bin/ls, running any terraform cmd does not work due to missing AWS creds to reach the tfstate bucket