version: 0.2

phases:
  pre_build:
    commands:
      - docker build -t terraform-shell .
  build:
    commands:
      - docker images
      - docker run terraform-shell /bin/terraform init
# trying to get it to do anything basede on created docker image 