version: 0.2
# try and load secrets as env vars 
env:
  secrets-manager:
    access_key: "arn:aws:secretsmanager:eu-central-1:654654627826:secret:access_key-GNbp0e"
    secret_key: "arn:aws:secretsmanager:eu-central-1:654654627826:secret:secret_key-yU41MM"
phases:
  pre_build:
    commands:
      - docker build -t terraform-shell .
      - echo $secret_key # is showing in cloudwatch as ***, which seems pretty okay  of cloudbuild logging 
      - echo $access_key
  build:
    commands:
      #- docker images
      - docker run terraform-shell terraform init 
# trying to get it to do anything based on created docker image, directory listing is shown when command = docker run terraform-shell /bin/pwd;/bin/ls, running any terraform cmd does not work due to missing AWS creds to reach the tfstate bucket