version: 0.2

phases:
  pre_build:
    commands:
      - docker build -t terraform-shell .
      - echo "Insert the breakpoint"
      - codebuild-breakpoint
  build:
    commands:
      - docker images
      - docker run terraform-shell /bin/terraform plan
# trying to get it to do anything based on created docker image .