version: 0.2

env:
  secrets-manager:
    access_key: "arn:aws:secretsmanager:eu-central-1:654654627826:secret:access_key-GNbp0e"
    secret_key: "arn:aws:secretsmanager:eu-central-1:654654627826:secret:secret_key-yU41MM"
phases:
  pre_build:
    commands:
      - docker build -t terraform-shell .
      - echo $access_key
  build:
    commands:
      - docker images
      - docker run terraform-shell /bin/terraform plan
# trying to get it to do anything based on created docker image .