version: 0.2
# try and load secrets as env vars 
#env:
  #secrets-manager:
   # access_key: "arn:aws:secretsmanager:eu-central-1:654654627826:secret:access_key-GNbp0e"
   # secret_key: "arn:aws:secretsmanager:eu-central-1:654654627826:secret:secret_key-yU41MM"
phases:
  pre_build:
    commands:
      - echo Retrieving AWS credentials from Secrets Manager...
      - export SECRETS=$(aws secretsmanager --region eu-central-1 get-secret-value --secret-id aws-creds --query SecretString --output text)
      #- echo $SECRETS
      - export AWS_ACCESS_KEY_ID=$(echo $SECRETS | jq -r '.Access_key_id')
      #- echo $AWS_ACCESS_KEY_ID
      - export AWS_SECRET_ACCESS_KEY=$(echo $SECRETS | jq -r '.Secret_access_key')
      #- echo $AWS_SECRET_ACCESS_KEY
      - docker build -t terraform-shell .
      #- echo $secret_key # is showing in cloudwatch as ***, which seems pretty okay  of cloudbuild logging 

  build:
    commands:
      #- docker images
      - docker run --rm -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e AWS_REGION=eu-central-1 terraform-shell destroy
     